server:
  port: 9991
spring:
  application:
    name: renre-check
  cloud:
    nacos:
      discovery:
        server-addr: 120.48.72.211:8848
        namespace: be188a42-2c90-487c-aece-802135d27942
  datasource:
    url: jdbc:mysql://120.48.66.56:3306/bank?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2916435196Liu@
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
